branch:
  trunk_name: "master"
  branch_type_A:
    tag:
      pattern: "v${versionnumber}"
      versionnumber: "{Major-version}.{Feature-version}.{Fix-version}"

artifact:
  - path: "/"
    artifact_name: "tnet"
    artifact_type: "lib"
    dependence_conf: "go.mod"

source:
  test_source:
    filepath_regex: [".*_test.go$"]
  auto_generate_source:
    filepath_regex:
      [
        ".*.pb.go$",
        ".*.trpc.go$",
      ]
  third_party_source:
    filepath_regex:
      [".*.h$", ".*.cpp$", ".*.a$", ".*.c$"]

code_review:
  restrict_labels:
    [
      "CR-编程规范",
      "CR-业务逻辑",
      "CR-边界逻辑",
      "CR-代码架构",
      "CR-性能影响",
      "CR-安全性",
      "CR-可测试性",
      "CR-可读性",
    ]
